FROM node:18-alpine 

WORKDIR /app

# Install dependencies needed for canvas package
RUN apk add --no-cache python3 py3-pip make g++ pkgconfig pixman-dev cairo-dev pango-dev jpeg-dev giflib-dev

COPY package*.json ./

RUN npm install --force

COPY . .

EXPOSE 3000

CMD ["npm","run","dev"]